name: Create a commit
description: Create a commit
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  outputs:
    description: |
      Prepare action's outputs
    required: true
  commit_message:
    description: |
      Commit message
    required: true
    default: Securefix
  pull_request_comment:
    description: |
      Pull Request comment
    required: true
    default: |
      :x: Securefix failed.
runs:
  using: composite
  steps:
    # Create and push a commit
    - if: ${{ steps.files.outputs.value != '' }}
      uses: suzuki-shunsuke/commit-action@9faad521ea6a1e768439ffbe6b25b6cb3fc1b181 # v0.0.6
      with:
        app_id: ${{inputs.app_id}}
        app_private_key: ${{inputs.app_private_key}}
        repository: ${{ fromJson(inputs.outputs).repository_full_name }}
        branch: ${{ fromJson(inputs.outputs).workflow_run.head_branch }}
        files: ${{ inputs.files }}
        commit_message: |
          ${{inputs.commit_message}}
          ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

    # Create a GitHub App token to report an error to a pull request
    - if: failure() && fromJson(inputs.outputs).pr != null
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      id: pr_token
      with:
        app_id: ${{inputs.app_id}}
        private_key: ${{inputs.app_private_key}}
        repositories: >-
          ["${{ fromJson(inputs.outputs).repository_name }}"]
        permissions: >-
          {
            "pull_requests": "write"
          }

    # Create a pull request comment to report an error
    - if: failure() && fromJson(inputs.outputs).pr != null
      shell: bash
      env:
        GH_TOKEN: ${{ steps.pr_token.outputs.token }}
        REPO: ${{ fromJson(inputs.outputs).repository_full_name }}
        PR_NUMBER: ${{ fromJson(inputs.outputs).pr.number }}
        COMMENT: ${{ inputs.pull_request_comment }}
      run: |
        gh pr comment \
          -R "$REPO" \
          -b "${COMMENT}" \
          [Workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" \
          "$PR_NUMBER"
